export const TYPES = {
    Bot: Symbol("Bot"),
    Client: Symbol("Client"),
    Token: Symbol("Token"),
    ChannelId: Symbol("ChannelId"),
    MessageResponder: Symbol("MessageResponder"),
    PingFinder: Symbol("PingFinder"),
    CoinToss: Symbol("CoinToss"),
    JoinService: Symbol("JoinService"),
    LeaveService: Symbol("LeaveService"),
    AddService: Symbol("AddService"),
    RemoveService: Symbol("RemoveService"),
    WhoService: Symbol("WhoService"),
    ResetService: Symbol("ResetService"),
};